services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8089:4200'
      - '49153:49153'
    volumes:
      - .:/app # Monta il codice sorgente all'interno del container
    environment:
      - NODE_ENV=development # Imposta l'ambiente di sviluppo
    stdin_open: true # Abilita l'input da parte dell'utente
    tty: true
